// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package ki

const (
	Version     = "v1.1.17"
	GitCommit   = "018e731"          // the commit JUST BEFORE the release
	VersionDate = "2023-10-05 21:52" // UTC
)
